# https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
name: 'DevSoutinho - Flutter Ci/CD Base Actions'
description: 'Greet someone'
icon: smartphone
color: orange

runs:
  using: "composite"
  steps:
    ## [Common_CI_Steps]
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-node@v2
      with:
        node-version: 18
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.3.4'
        channel: 'stable' # or: 'beta', 'dev' or 'master'
    - name: Install melos
      shell: bash
      run: dart pub global activate melos
    ## ======
